apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - port: 20
      name: ftps-date
      targetPort: 20
      nodePort: 20
    - port: 21
      name: ftps-cmd
      targetPort: 21
      nodePort: 21
    - port: 30020
      name: ftps-pasvmin
      targetPort: 30020
      nodePort: 30020
    - port: 30021
      name: ftps-pasvmax
      targetPort: 30021
      nodePort: 30021

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps-image
          imagePullPolicy: Never
          ports:
            - containerPort: 20
              name: ftps-data
            - containerPort: 21
              name: ftps-cmd
            - containerPort: 30020
              name: ftps-pasvmin
            - containerPort: 30021
              name: ftps-pasvmax
      env:
        - name: ip
          value: $ip