apiVersion: v1
kind: Service
metadate:
  name: ftps-service
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - port: 20
      name: ftps-date
      targetPort: 20
      nodePort: 20
    - port: 21
      name: ftps-cmd
      targetPort: 21
      nodePort: 21

---

apiVersion: apps/v1
kind: Deployment
metadate:
  name: ftps-Deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadate:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps-image
          imagePullPolicy: Never
          ports:
            - containerPort: 20
              name: ftps-data
            - containerPort: 21
              name: ftps-cmd