# https://kubernetes.io/ko/docs/concepts/services-networking/service/
# https://kubernetes.io/ko/docs/concepts/overview/working-with-objects/labels/
# https://kubernetes.io/ko/docs/concepts/services-networking/connect-applications-service/

# https://kubernetes.io/ko/docs/concepts/workloads/controllers/deployment/
# https://arisu1000.tistory.com/27833

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
      nodePort: 80
    - port: 443
      name: https
      targetPort: 443
      nodePort: 443
    - port: 22
      name: ssh
      targetPort: 22
      nodePort: 22

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh