apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-nginx
# spec:
#   selector:
#     matchLabels:
#       run: my-nginx
#   replicas: 2
#   template:
#     metadata:
#       labels:
#         run: my-nginx
#     spec:
#       containers:
#       - name: my-nginx
#         image: nginx
#         ports:
#         - containerPort: 80

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
# 		name: nginx-deployment
# 		labels:
# 				app: nginx
# spec:
# 		selector:
# 				matchLabels:
# 						app: nginx
# 		replicas: 1
# 		template:
# 				metadata:
# 						name: nginx-pod
# 						labels:
# 								app: nginx
# 				spec:
# 						containers:
# 								- name: nginx-container
# 								  image: nginx-image
# 								  imagePullPolicy: Never
# 								  ports:
# 										  - containerPort: 80
# 											name: nginx-http
# 										  - containerPort: 443
# 											name: nginx-https
# 										  - containerPort: 22
# 											name: nginx-ssh